<?php
/**
 * -------------------------------------------------
 * 买家中心 - 关注的商品
 * -------------------------------------------------
 * Create by Lazycat <673090083@qq.com>
 * -------------------------------------------------
 * 2017-01-17
 * -------------------------------------------------
 */
namespace Mobile\Controller;
use Think\Controller;
class FavGoodsController extends CommonController {

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->check_logined();
    }

    /**
     * 关注商品列表
     */
    public function index(){
        $data = I('get.');
        $data['openid'] = session('user.openid');

        $res = $this->doApi2('/FavGoods/goods',$data);
        $this->assign('pagelist',$res['data']);
        //var_dump($res);
        $this->display();
    }

    /**
     * 分页
     */
    public function goods_page(){
        $data = I('get.');
        $data['openid'] = session('user.openid');

        $res = $this->doApi2('/FavGoods/goods',$data);
        $this->ajaxReturn($res);
    }

    /**
     * 取消关注
     */
    public function delete(){
        //C('DEBUG_API',true);
        $res = $this->doApi2('/FavGoods/delete',['id' => I('post.id'),'openid' => session('user.openid')]);
        $this->ajaxReturn($res);
    }


}