<?php
/**
 * -------------------------------------------------
 * 买家中心 - 关注的店铺
 * -------------------------------------------------
 * Create by Lazycat <673090083@qq.com>
 * -------------------------------------------------
 * 2017-01-18
 * -------------------------------------------------
 */
namespace Mobile\Controller;
use Think\Controller;
class FavShopController extends CommonController {

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->check_logined();
    }

    /**
     * 关注的店铺列表
     */
    public function index(){
        $data = I('get.');
        $data['openid'] = session('user.openid');

        $res = $this->doApi2('/FavShop/shop',$data);
        $this->assign('pagelist',$res['data']);
        //print_r($res);
        $this->display();
    }

    /**
     * 分页
     */
    public function shop_page(){
        $data = I('get.');
        $data['openid'] = session('user.openid');

        $res = $this->doApi2('/FavShop/shop',$data);
        $this->ajaxReturn($res);
    }

    /**
     * 取消关注
     */
    public function delete(){
        //C('DEBUG_API',true);
        $res = $this->doApi2('/FavShop/delete',['id' => I('post.id'),'openid' => session('user.openid')]);
        $this->ajaxReturn($res);
    }


}