<?php
/**
 * -------------------------------------------------
 * 我的(买家中心)
 * -------------------------------------------------
 * Create by Lazycat <673090083@qq.com>
 * -------------------------------------------------
 * 2017-01-13
 * -------------------------------------------------
 */
namespace Mobile\Controller;
use Think\Controller;
class UcenterController extends CommonController {

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->check_logined();
    }

    /**
     * 买家中心首页
     */
    public function index(){
		//C('DEBUG_API',true);
		//消息数量
		$count = 0;
		$res = $this->doApi2('/Notice/notice_count',['openid' => session('user.openid')]);
		foreach($res['data'] as $v){
			if($v['is_read']==0){
				$count += $v['num'];
			}
		}
		$this->assign('count',$count > 99 ? 99 : $count);
        /*
		$res = $this->doApi2('/Im/have_message',['openid' => session('user.openid')]);
		$count += $res['code'];
		$this->assign('count',$count > 99 ? 99 : $count);
        */
		

//        $account = $this->doApi2('/Erp/account',['erp_uid' => session('user.erp_uid')]);
//        $this->assign('account',$account['data']);
        //var_dump($account);

        //C('DEBUG_API',true);
        $total = $this->doApi2('/Total/buyer_total',['openid' => session('user.openid')]);
        $this->assign('total',$total['data']);
        //print_r($total);
	

        //猜您喜欢
        //C('DEBUG_API',true);
        $love = $this->doApi2('/Search/love',['num' => 8]);
        $this->assign('love',$love['data']);

        //var_dump($love);

        $this->display();
    }

	
	/**
     * subject: 获取方圆的消息数量
     * author: liangfeng
     * day: 2017-06-02 
     */
	public function ajax_im_count(){
		$res = $this->doApi2('/Im/have_message',['openid' => session('user.openid')]);
		$this->ajaxReturn($res);
	}

}