<?php
/**
 * -------------------------------------------------
 * 修改登录密码
 * -------------------------------------------------
 * Create by lizuheng <673090083@qq.com>
 * -------------------------------------------------
 * 2017-02-06
 * -------------------------------------------------
 */
namespace Mobile\Controller;
use Think\Controller;
class UserController extends CommonController {
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->check_logined();
    }
	
    /**
     * 发送验证码
     */
    public function send_code(){
		$data['mobile'] = session('user')['mobile'];
	    $res = $this->doApi2('/Erp/smscode',$data);
		$this->ajaxReturn($res);
    }
	
	/**
     * 找回安全密码页面
     */
    public function forget_safe_password(){
		$this->display();
    }
  
    /**
     * 保存新的安全密码
     */
    public function forgot_pay_password(){
		if(I('post.password2') != I('post.password')){
			$this->ajaxReturn(['code' => 0,'msg'=>'新密码和确认密码不一致']);
		}
		$data['password']  = $this->password(I('post.password'));
		$data['smscode']   = I('post.smscode');
		$data['mobile']    = session('user')['mobile'];
		$data['openid']    = session('user')['openid'];

        $res = $this->doApi2('/Erp/forgot_pay_password',$data);
        $this->ajaxReturn($res);
    }
	
    /**
     * 修改登录密码页面
     */
    public function edit_login_password(){
		$this->display();
    }
  
    /**
     * 保存新的登录密码
     */
    public function save_login_password(){
		if(I('post.password2') != I('post.password')){
			$this->ajaxReturn(['code' => 0,'msg'=>'新密码和确认密码不一致']);
		}
		$data['opassword'] = $this->password(I('post.opassword'));
		$data['password']  = $this->password(I('post.password'));
		$data['smscode']   = I('post.smscode');
		$data['mobile']    = session('user')['mobile'];
		$data['openid']    = session('user')['openid'];

        $res = $this->doApi2('/Erp/change_password',$data);
        $this->ajaxReturn($res);
    }
	/**
     * 设置安全密码页面
     */
    public function set_safe_password(){
		$this->display();
    }
	
	/**
     * 保存安全密码
     */
    public function save_set_password(){
		if(I('post.password2') != I('post.password')){
			$this->ajaxReturn(['code' => 0,'msg'=>'新密码和确认密码不一致']);
		}

		$data['password'] = $this->password(I('post.password'));
		$data['smscode']  = I('post.smscode');
		$data['mobile']   = session('user')['mobile'];
		$data['openid']   = session('user')['openid'];

        $res = $this->doApi2('/Erp/set_pay_password',$data);
        $this->ajaxReturn($res);
    }
	/**
     * 修改安全密码页面
     */
    public function edit_safe_password(){
		$this->display();
    }
	
    /**
     * 保存新的安全密码
     */
    public function save_safe_password(){
		if(I('post.password2') != I('post.password')){
			$this->ajaxReturn(['code' => 0,'msg'=>'新密码和确认密码不一致']);
		}
		$data['opassword'] = $this->password(I('post.opassword'));
		$data['password']  = $this->password(I('post.password'));
		$data['smscode']   = I('post.smscode');
		$data['mobile']    = session('user')['mobile'];
		$data['openid']    = session('user')['openid'];
		
        $res = $this->doApi2('/Erp/change_pay_password',$data);
        $this->ajaxReturn($res);
    }
}