<?php
/**
 * Created by PhpStorm.
 * User: dttx
 * Date: 2017/2/25
 * Time: 9:31
 */

namespace Common\Form;

/**
 * 表单组
 *
 * Class FormGroup
 * @package Common\Form
 */

class FormGroup extends Form
{

    public static $_instance;   //单例

    public $_group  =   []; //组


    function __construct($formOptions = null)
    {
        if (!isset($formOptions['errorBox'])) $formOptions['errorBox'] = '#error-box';
        parent::__construct($formOptions);
    }

    public static function getInstance($formOptions = null)
    {
        return new self($formOptions);
    }

    /**
     * 组
     *
     * @param $options
     * @return $this
     */
    public function group($options) {
        $this->_group['title'][] = $options['title'];
        $this->_group['html'][] = $this->_html;
        $this->_html = '';
        return $this;
    }

    public function create()
    {
        //return parent::create(); // TODO: Change the autogenerated stub
        $data['html']   = str_replace('{body}', Html::getInstance()->group($this->_group), Html::getInstance($this->_formOptions)->formHtml());
        $jsBefore = '';
        if ($this->_datetimeJs === true) $jsBefore .= Js::dateJs();
        if ($this->_uploadJs === true) $jsBefore .= Js::uploadJs();
        if ($this->_checkboxCss) $jsBefore .= Js::checkboxCss();
        if ($this->_script) $this->_formOptions['script'] = $this->_script;
        $data['js']     = Js::create($this->_js . ($this->_formOptions['ajax'] == true ? Js::ajaxSubmit($this->_formOptions) : Js::submit($this->_formOptions)), $jsBefore);
        if ($jsBefore) $jsBefore = null;
        $this->free();
        return $data;
    }
}